spring:
  cloud:
    gateway:
      routes:
        - id: ms_auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*),/$\{segment}
